"""
Example Snakefile. This should be replaced by corpus specifik snakefiles later on.

Run with e.g. `snakemake TEXT`
"""
# Import default configuration
import os
include: os.path.join(os.getenv('SPARV_PIPELINE_PATH'), "config.snake")

# Info about input and resulting annotations... not needed anymore?
# Format: (input_elem:attribute, [output_file])
# existing_structural_elements = ["text", "text:forfattare", "text:date"]

# Format: (input_file, output_attribute)
positional_annotations = ["word", "pos", "msd",
                          "baseform", "sense", "lemgram",
                          "compwf", "complemgram",
                          "sentiment", "sentimentclass",
                          "deprel", "dephead", "ref",
                          "blingbring", "swefn"]

structural_annotations = ["ne.ex", "ne.type", "ne.subtype", "ne.name",
                          "sentence", "sentence.id", ("sentence.geocontext", "sentence:_geocontext"),
                          "paragraph", ("paragraph.geocontext", "paragraph:_geocontext"),
                          "text", ("text.forfattare", "text:author"),
                          "text.blingbring", "text.swefn",
                          "text.lix", "text.ovix", "text.nk",
                          "text.datefrom", "text.dateto", "text.timefrom", "text.timeto"
                          ]

datefrom = "text.date"
dateto = "text.date"
dateformat = "%Y-%m-%d"

# analysis = "sv-1800"

# Import rule files
# TODO: Build a mechanism that figures out automatically what files to import
include: os.path.join(sparv_snakefile_dir, "utils.snake")
include: os.path.join(sparv_snakefile_dir, "xmlparser.snake")

# include: os.path.join(sparv_snakefile_dir, "number.snake")
# include: os.path.join(sparv_snakefile_dir, "segment.snake")
# include: os.path.join(sparv_snakefile_dir, "hunpos.snake")
# include: os.path.join(sparv_snakefile_dir, "malt.snake")
# include: os.path.join(sparv_snakefile_dir, "saldo.snake")
# include: os.path.join(sparv_snakefile_dir, "compound.snake")
# include: os.path.join(sparv_snakefile_dir, "wsd.snake")
# include: os.path.join(sparv_snakefile_dir, "sentiment.snake")
# include: os.path.join(sparv_snakefile_dir, "swener.snake")
# include: os.path.join(sparv_snakefile_dir, "geo.snake")
# include: os.path.join(sparv_snakefile_dir, "readability.snake")
# include: os.path.join(sparv_snakefile_dir, "lexical_classes.snake")
# include: os.path.join(sparv_snakefile_dir, "dateformat.snake")
# include: os.path.join(sparv_snakefile_dir, "cwb.snake")
