
ifneq ($(filter $(lang),as ca cy de en es fr gl it no pt ru sl),)
  analysis = fl
else
  ifneq ($(filter $(lang),bg et fi la nl pl ro sk),)
    analysis = tt
  else
    analysis = none
  endif
endif
