ifeq ($(origin corpus), undefined)
  $(error Argument 'corpus' is undefined. Specify corpus by appending corpus=name to the command line)
endif

# Split corpus argument into parts
parts := $(subst /, ,$(corpus))

# Set corpus name to last part of path
override corpus := $(lastword $(parts))

# Make sure the corpus path has a trailing slash
empty :=
space := $(empty) $(empty)
root = $(subst $(space),/,$(strip $(parts)))/
