# This file should be included at the top of your corpus Makefile

################################################################################
#                                CONFIGURATION                                 #
################################################################################

# Path to the pipeline
SPARV_PIPELINE_PATH ?=
SPARV_MODELS ?= $(SPARV_PIPELINE_PATH)/models
SPARV_PYTHON ?= $(SPARV_PIPELINE_PATH)
SPARV_BIN ?= $(SPARV_PIPELINE_PATH)/bin
VENV_PATH = $(dir $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST)))/../venv

# Corpus Workbench registry and data directories
export CORPUS_REGISTRY ?=
export CWB_DATADIR ?=

# Remote host name for installation of both corpus data and database
remote_host =

# Paths on remote server (targets for install_corpus)
remote_cwb_datadir =
remote_cwb_registry =

# Export hosts and paths (targets for install_export and install_export_original)
export_host =
export_path =
export_original_host =
export_original_path =

# Database name for relations, lemgram index and timespan
mysql_dbname =

# Append bin path to PATH
export PATH := $(SPARV_BIN):$(PATH)

# Set python path and python executable in virtual environment
export PYTHONPATH := $(PYTHONPATH):$(SPARV_PYTHON)

ifndef python
python = $(VENV_PATH)/bin/python3 -u
endif

# The initial chmod for directories. Defaults to the value 775
dir_chmod = 775

################################################################################
#                                    MODELS                                    #
################################################################################

bettertokenizer_config = $(SPARV_MODELS)/bettertokenizer.sv
punkt_model_sv = $(SPARV_MODELS)/punkt-nltk-svenska.pickle
punkt_model_en = $(SPARV_MODELS)/punkt-nltk-english.pickle
punkt_model := $(punkt_model_sv)
hunpos_model = $(SPARV_MODELS)/hunpos.suc3.suc-tags.default-setting.utf8.model
hunpos_morphtable = $(SPARV_MODELS)/hunpos.saldo.suc-tags.morphtable
hunpos_morphtable_patterns = $(SPARV_MODELS)/hunpos.suc.patterns
hunpos_morphtable_swedalin = $(SPARV_MODELS)/hunpos.dalinm-swedberg.saldo.suc-tags.morphtable
# tag_mapping = parole_to_suc
saldo_model = $(SPARV_MODELS)/saldo.pickle
saldo_compound_model = $(SPARV_MODELS)/saldo.compound.pickle
dalin_model = $(SPARV_MODELS)/dalin.pickle
swedberg_model = $(SPARV_MODELS)/swedberg.pickle
nst_comp_model = $(SPARV_MODELS)/nst.comp.pos.pickle
stats_model = $(SPARV_MODELS)/stats.pickle
malt_model = $(SPARV_MODELS)/swemalt-1.7.2.mco
malt_jar = maltparser-1.7.2/maltparser-1.7.2.jar
wsd_jar = wsd/saldowsd.jar
wsd_sense_model = $(SPARV_MODELS)/wsd/ALL_512_128_w10_A2_140403_ctx1.bin
wsd_context_model = $(SPARV_MODELS)/wsd/lem_cbow0_s512_w10_NEW2_ctx.bin
blingbring_model = $(SPARV_MODELS)/blingbring.pickle
blingbring_freq_model = $(SPARV_MODELS)/blingbring.freq.gp2008+suc3+romi.pickle
blingbring_class_set = "bring"
swefn_model = $(SPARV_MODELS)/swefn.pickle
swefn_freq_model = $(SPARV_MODELS)/swefn.freq.gp2008+suc3+romi.pickle
pos_limit = "NN VB JJ AB"
sentiment_model = $(SPARV_MODELS)/sensaldo.pickle
tt_bin = treetagger/tree-tagger
tt_model = $(SPARV_MODELS)/treetagger/$(lang).par
fl_config = $(SPARV_MODELS)/freeling/$(lang).cfg  # FreeLing
geo_model = $(SPARV_MODELS)/geo.pickle
geo_language = sv

non_word_pos = "MAD MID PAD PUNCT SYM"
noun_pos = "NN NOUN PP ADP PC" # nouns, prepositions, participles
verb_pos = "PN PRON AB ADV VB VERB" # pronouns, adverbs, verbs

################################################################################
#                               DEFAULT SETTINGS                               #
################################################################################

default_token_segmenter = better_word
default_sentence_segmenter = punkt_sentence

################################################################################
#                             DEFAULT ANNOTATIONS                              #
################################################################################

# These variables are optional and only used for convenience.
# We do not use := here, since we want the user to be able to append to the
# different variables.


# Positional annotations

_saldo_annotations = baseform lemgram sense prefix suffix compwf complemgram
_saldo             = lemma    lex     sense prefix suffix compwf complemgram

_dep_annotations = ref dephead.ref deprel
_dep             = ref dephead     deprel

_lexical_class_annotations = blingbring swefn
_lexical_class             = blingbring swefn

_sentiment_annotations = sentiment sentimentclass
_sentiment             = sentiment sentimentclass

_default_annotations := word pos msd $(_saldo_annotations) $(_dep_annotations) $(_lexical_class_annotations)
_default             := word pos msd $(_saldo) $(_dep) $(_lexical_class)


# Structural annotations

_ne_annotations = ne.ex ne.type ne.subtype ne.name
_ne             = ne:ex ne:type ne:subtype ne:name

_time_annotations = text.datefrom text.dateto text.timefrom text.timeto
_time             = text:datefrom text:dateto text:timefrom text:timeto

_lexical_class_doc_annotations = text.blingbring text.swefn
_lexical_class_doc             = text:blingbring text:swefn

_default_smallest_annotations = $(_ne_annotations)
_default_smallest             = $(_ne)

_default_sentence_annotations = sentence.id sentence.geocontext
_default_sentence             = sentence:id sentence:_geocontext

_default_paragraph_annotations = paragraph paragraph.geocontext
_default_paragraph             = paragraph paragraph:_geocontext

_default_readability_annotations = text.lix text.ovix text.nk
_default_readability             = text:lix text:ovix text:nk

_default_text_annotations = $(_time_annotations) $(_lexical_class_doc_annotations) $(_default_readability_annotations)
_default_text             = $(_time)             $(_lexical_class_doc)             $(_default_readability)

_default_structs_annotations = $(_default_smallest_annotations) $(_default_sentence_annotations) $(_default_paragraph_annotations) $(_default_text_annotations)
_default_structs             = $(_default_smallest)             $(_default_sentence)             $(_default_paragraph)             $(_default_text)


# Default annotations
vrt_columns_annotations = $(_default_annotations)
vrt_columns             = $(_default)

vrt_structs_annotations = $(_default_structs_annotations)
vrt_structs             = $(_default_structs)

################################################################################

# Display help when no target is specified
default: help
